<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-0FVAB1O" failures="1" tests="2" name="Test" time="94.514" errors="0" timestamp="17 Jun 2024 13:07:16 GMT">
  <testcase classname="test.SampleTest" name="Sample" time="1.446">
    <failure type="java.lang.AssertionError" message="null">
      <![CDATA[java.lang.AssertionError: null
	at test.SampleTest.Sample(SampleTest.java:29)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:840)
... Removed 12 stack frames]]>
    </failure>
  </testcase> <!-- Sample -->
  <testcase classname="test.LoginTest" name="login" time="8.49"/>
</testsuite> <!-- Test -->
